"""v6

Revision ID: cd4d01c3f73e
Revises: 
Create Date: 2022-09-22 14:48:14.153276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4d01c3f73e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('td_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lastlogin', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('td_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=120), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['td_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('td_pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=120), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['td_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('td_todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['td_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('td_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('history', sa.Integer(), nullable=False),
    sa.Column('dropped_at', sa.DateTime(), nullable=False),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['history'], ['td_history.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['td_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('history'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('td_session')
    op.drop_table('td_todo')
    op.drop_table('td_pin')
    op.drop_table('td_history')
    op.drop_table('td_user')
    # ### end Alembic commands ###
